### ISSUE TITLE
1.2.4 Pre-release on Phpbb 3.3 : UCP Notification error

### ISSUE THREAD

**Issue by kamiben** [jasoloz/advancedpolls#10]
Hi, 
A big thanks for the update !
I have installed the extension in a copy of my main forum. 
There is an error when accessing : user control panel >  Board preferences > User notification options

I guess disabling the code relative to notifications would do the trick but if you need testing I can try to help.

`
Fatal error: Uncaught TypeError: Argument 1 passed to phpbb\notification\type\base::__construct() must implement interface phpbb\db\driver\driver_interface, instance of phpbb\user_loader given, called in /beta/forum/cache/production/container_4335734bbdd20f586549a504dff5f80c.php on line 4208 and defined in /beta/forum/phpbb/notification/type/base.php:87 Stack trace: #0 /beta/forum/cache/production/container_4335734bbdd20f586549a504dff5f80c.php(4208): phpbb\notification\type\base->__construct(Object(phpbb\user_loader), Object(phpbb\db\driver\factory), Object(phpbb\cache\driver\file), Object(phpbb\user), Object(phpbb\auth\auth), Object(phpbb\config\db), './', 'php', 'ybdk_notificati...', 'ybdk_notificati...', 'ybdk_user_notif...') #1 /beta/forum/vendor/symfony/dependency-injection/Container.php(306): phpbb_cache_container->getWolfsblvt_Advance in /beta/forum/phpbb/notification/type/base.php on line 87`

**Comment by jasoloz** [comment]
The problem was resolved with the version 1.2.4.1.
