### ISSUE TITLE
Can't build container

### ISSUE THREAD

**Issue by alwaysontheice** [jasoloz/advancedpolls#9]
I'm getting the following error message when attempting to run the extension on 3.3.0:

phpBB encountered an error building the container due to an installed extension. For this reason, all extensions have been temporarily disabled. Please try purging your forum cache. All extensions will automatically be re-enabled once the container error is resolved. If this error continues, please visit phpBB.com for support.

Exception: The file "/home/redacted/phpbb3/ext/wolfsblvt/advancedpolls/config/services.yml" does not contain valid YAML: The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 5 (near "- @wolfsblvt.advancedpolls.advancedpolls").

#0 /home/redacted/phpbb3/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(117): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadFile('/home/redacted/...')
#1 /home/redacted/phpbb3/phpbb/extension/di/extension_base.php(99): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('services.yml')
#2 /home/redacted/phpbb3/phpbb/extension/di/extension_base.php(63): phpbb\extension\di\extension_base->load_services(Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#3 /home/redacted/phpbb3/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(71): phpbb\extension\di\extension_base->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#4 /home/redacted/phpbb3/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#5 /home/redacted/phpbb3/vendor/symfony/dependency-injection/Compiler/Compiler.php(140): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#6 /home/redacted/phpbb3/vendor/symfony/dependency-injection/ContainerBuilder.php(789): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#7 /home/redacted/phpbb3/phpbb/di/container_builder.php(203): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#8 /home/redacted/phpbb3/common.php(115): phpbb\di\container_builder->get_container()
#9 /home/redacted/phpbb3/adm/index.php(23): require('/homeredacted/...')
#10 {main}

**Comment by jasoloz** [comment]
Yes, I am aware that the extension is incompatible with version 3.3 because of the error indicated in services.yml: The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar. The fix consists on adding quotes to the elements with @, as for example, replacing **- @user** with **- '@user'** and so on). Also the items with "%" need quotes. This way the file services.yml will contain valid YAML. I need to do more checks before releasing a version compatible with 3.3, but that fix will allow you to do the same and found bugs I have not yet seen.  ;)
